name: Deploy

on:
  workflow_run:
    workflows:
      - "Build"
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Image to Sever
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/kingblue
            docker compose --ansi=never pull
            docker compose --ansi=never up -d
